# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# 使用其他来源地址
source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'
# 使用官方默认地址（默认）
source 'https://github.com/CocoaPods/Specs.git'

target 'Ees' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for Ees
  pod 'Masonry', '~> 1.1.0'
  pod 'AFNetworking', '~> 3.1.0'
  pod 'Reachability', '~> 3.2'
  pod 'MJRefresh', '~> 3.1.15.1'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'JSONModel', '~> 1.7.0'
  pod 'SDWebImage', '~> 4.2.2'
  pod 'YLGIFImage', '~> 0.11'
  pod 'UMCCommon'
  #pod 'UMCSecurityPlugins'
  pod 'UMCAnalytics'
  pod 'FLAnimatedImage', '~> 1.0'
  pod 'BabyBluetooth','~> 0.7.0'
  
  
  # 使用其他来源
  pod 'ALBBMediaService',       '~>3.7.2.5'
  
end
